### ISSUE TITLE
모바일 웹페이지에서 버튼들이 화면에서 벗어나는 표현됨

### ISSUE THREAD

**Issue by neoqmin** [WizardFactory/BlogSyncer#349]
##### iPhone5c safari에서 blogsync 웹 접속시 로그인 화면에서 버튼들이 오른쪽으로 넘어가는 증상
style.css :76
```css
.btn-blog {
    min-width: 300px;
    max-width: 300px;
    margin-bottom: 5px;
    display: block;
    text-align: left;
    vertical-align: middle;
}
```
위의 stylesheet 코드에서 min-width를 줄일 필요가 있어 보입니다.

아래와 같이 bootstrap.min.css:7 의 padding 값도 영향을 줍니다.
```css
.container {
    margin-right: auto;
    margin-left: auto;
    padding-left: 15px;
    padding-right: 15px;
}
```
